### ISSUE TITLE
[Neoforge 1.21.3] balloon disappears when hit

### ISSUE THREAD

**Issue by jshipley** [kodiitulip/fancy-balloons#2]
I crafted a balloon, placed it, but wanted to move it. I tried hitting it once, and it disappeared without leaving any balloon item.

**Comment by kodiitulip** [comment]
Hi! Thanks for reporting this.
It's been a while since I worked on this datapack (blame my lack of free time and motivation)

Probably some issue with the hitting detection. The original code tries to check if the player is in creative or not to decide to drop the item, but I now see that it causes issues.

When I have enough time I'll fix it!

**Comment by kodiitulip** [comment]
The issue has been fixed on the new available patch on modrinth and here on github. Any other problem you can always report here S2.
